### ISSUE TITLE
Requesting GPUs fails due to invalid gres request

### ISSUE THREAD

**Issue by thomasmfish** [DiamondLightSource/ParProcCo#86]
Here is an the error I received:
```
16:35:43 19-06-2024 -       slurm_client:_has_openapi_errors -    ERROR -     : description='Batch job submission failed' error='Invalid generic resource (gres) specification' error_number=2072 source='slurm_submit_batch_job()'
```

The only difference was I specified `gpus=1` in JobResources. This leads to `'tres_per_task': 'gres/gpu:1'`, which seems to not be correct. I've created a branch adding a couple of tests that add gpus for a simple example [add-gpu-tests](https://github.com/DiamondLightSource/ParProcCo/tree/add-gpu-tests)

**Comment by thomasmfish** [comment]
`'tres_per_job': 'gres/gpu:1'` works, so something is odd with specifying `tres_per_task`.

**Comment by PeterC-DLS** [comment]
I agree. Adding `tasks` fully specifies the requested allocation so SLURM will be happy.
